/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumbs: typeof import('./../views/Layout/components/Header/components/breadCrumbs.vue')['default']
    Drawer: typeof import('./../views/Layout/components/Drawer/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./../views/Layout/components/Header/index.vue')['default']
    Line: typeof import('./../views/Home/components/line.vue')['default']
    MenuItem: typeof import('./../views/Layout/Menu/components/MenuItem.vue')['default']
    MenuLogo: typeof import('./../views/Layout/Menu/components/MenuLogo.vue')['default']
    Pie: typeof import('./../views/Home/components/pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./../views/Layout/components/Header/components/setting.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagViews: typeof import('./../views/Layout/components/TagViews/index.vue')['default']
  }
}
